### ISSUE TITLE
I can't install any updates in version 1.21

### ISSUE THREAD

**Issue by flezus** [OriginCode/VanillaEnhanced#2]
Whenever I try to install the modpack through Prism Launcher, an error appears.
![error](https://github.com/user-attachments/assets/6b52b845-ba6d-456f-8dac-ab91ea4709eb)

**Comment by OriginCode** [comment]
@flezus huh, it works on my computer. Can you try to locate the log file of PrismLauncher and send it here? Were you installing the modpack from Modrinth? And which version (date) of the modpack were you trying to install?

**Comment by flezus** [comment]
I will send you the log files. I'm using Prism and downloading from the modrinth source, the version is as follows: **1.21-20240726**
I tried to install old versions, I couldn't, I was only able to install the version 1.20 that was released today, I believe this bug has been happening for a long time, I was trying to install the modpack a few weeks ago and I couldn't, but I only now had the courage to open it a bug report.
[PrismLauncher-0.log](https://github.com/user-attachments/files/16402034/PrismLauncher-0.log)

**Comment by OriginCode** [comment]
> I will send you the log files. I'm using Prism and downloading from the modrinth source, the version is as follows: **1.21-20240726** I tried to install old versions, I couldn't, I was only able to install the version 1.20 that was released today, I believe this bug has been happening for a long time, I was trying to install the modpack a few weeks ago and I couldn't, but I only now had the courage to open it a bug report. [PrismLauncher-0.log](https://github.com/user-attachments/files/16402034/PrismLauncher-0.log)

Got it, I'll fix it in the next release. Thank you very much for reporting the issue.

**Comment by OriginCode** [comment]
Should be fixed in the newest release https://modrinth.com/modpack/vanillaenhanced/version/LF4L3lxg .

Closing for now.

**Comment by flezus** [comment]
Thank you SO MUCH for the fix!
I believe the mods:
language-reload-1.6.1+1.21
lazy-language-loader-0.3.7

They are conflicting, making the game crash

**Comment by OriginCode** [comment]
@flezus Got it, I will open another issue for it. Thank you for reporting!

**Comment by OriginCode** [comment]
> Thank you SO MUCH for the fix! I believe the mods: language-reload-1.6.1+1.21 lazy-language-loader-0.3.7
> 
> They are conflicting, making the game crash

#3
